<?php
function peaches_ecwid_product_render($attr, $content) {
	if(array_key_exists('id', $attr)) {
		$product = Ecwid_Product::get_by_id($attr['id']);

		$classes = join(' ', [
			(array_key_exists('classes', $attr) ? $attr['classes'] : ''),
			(array_key_exists('className', $attr) ? $attr['className'] : '')
		]);

		$sub_title = '';
		foreach ( (array) $product->attributes as $attribute ) {
			if($attribute->name == 'Ondertitel') {
				$sub_title = $attribute->valueTranslated->nl;
			}
		}
		$product_url = get_site_url() . '/winkel/' . $product->autogeneratedSlug . '/';
		return '<div class="card h-100 border-0 '.$classes.'" onclick="window.location.href=\''.$product_url.'\'; return false;">'
			.'<div class="ratio ratio-1x1">'
				.'<img class="card-img-top " src="'.esc_url( $product->thumbnailUrl ).'"/>'
				.'<div class="card-img-top " itemprop="image" data-force-image="true"></div>'
			.'</div>'
			.'<div class="card-body p-2 p-md-3">'
				.'<h5 class="card-title">'.$product->name.'</h5>'
				.'('.$sub_title.')'
			.'</div>'
			.'<div class="card-footer border-0">'
				.'<div class="card-text fw-bold">&euro; '.$product->price.'</div>'
			.'</div>'
		.'</div>';
	} else {
		return '<div>Product could not be loaded</div>';
	}
}
