<?php
/**
 * Media Tags Manager class
 *
 * Manages predefined media tags that can be used across products.
 * Each tag represents a media type (hero_image, size_chart etc.)
 * and products can assign one media item per tag.
 *
 * @package PeachesEcwidBlocks
 * @since   0.2.0
 */

if (!defined('ABSPATH')) {
	exit;
}

/**
 * Class Peaches_Media_Tags_Manager
 *
 * @package PeachesEcwidBlocks
 * @since   0.2.0
 */
class Peaches_Media_Tags_Manager {

	/**
	 * Option name for storing media tags
	 */
	const TAGS_OPTION = 'peaches_ecwid_media_tags';

	/**
	 * Default media tags
	 */
	const DEFAULT_TAGS = array(
		'hero_image' => array(
			'label' => 'Hero Image',
			'description' => 'Main featured image for the product',
			'category' => 'primary'
		),
		'size_chart' => array(
			'label' => 'Size Chart',
			'description' => 'Product sizing information',
			'category' => 'reference'
		),
		'product_video' => array(
			'label' => 'Product Video',
			'description' => 'Video demonstrating the product',
			'category' => 'media'
		),
		'ingredients_image' => array(
			'label' => 'Ingredients Image',
			'description' => 'Visual ingredients list or nutrition facts',
			'category' => 'reference'
		),
		'packaging_image' => array(
			'label' => 'Packaging Image',
			'description' => 'Product packaging or box image',
			'category' => 'secondary'
		)
	);

	/**
	 * Constructor.
	 */
	public function __construct() {
		$this->init_hooks();
		$this->maybe_initialize_default_tags();
	}

	/**
	 * Initialize hooks.
	 */
	private function init_hooks() {
		// Remove the separate admin menu - now integrated into tabs
		// add_action('admin_menu', array($this, 'add_admin_menu'), 25);

		add_action('admin_init', array($this, 'handle_form_submission'));
		add_action('wp_ajax_add_media_tag', array($this, 'ajax_add_media_tag'));
		add_action('wp_ajax_delete_media_tag', array($this, 'ajax_delete_media_tag'));
		add_action('wp_ajax_update_media_tag', array($this, 'ajax_update_media_tag'));
	}

	/**
	 * Maybe initialize default tags on first run.
	 */
	private function maybe_initialize_default_tags() {
		$existing_tags = get_option(self::TAGS_OPTION, array());

		if (empty($existing_tags)) {
			update_option(self::TAGS_OPTION, self::DEFAULT_TAGS);
		}
	}

	/**
	 * Enqueue scripts specifically for the tab context
	 *
	 * @since 0.2.0
	 *
	 * @param string $hook Current admin page hook
	 *
	 * @return void
	 */
	public function enqueue_tab_scripts($hook) {
		// Custom script only - no custom CSS needed with Bootstrap
		wp_enqueue_script(
			'peaches-media-tags-admin',
			PEACHES_ECWID_ASSETS_URL . 'js/admin-media-tags.js',
			array('jquery'),
			PEACHES_ECWID_VERSION,
			true
		);

		wp_localize_script('peaches-media-tags-admin', 'MediaTagsParams', array(
			'ajaxUrl' => admin_url('admin-ajax.php'),
			'nonce' => wp_create_nonce('media_tags_nonce'),
			'strings' => array(
				'confirmDelete' => __('Are you sure you want to delete this tag? This action cannot be undone.', 'peaches'),
				'editTag' => __('Edit Tag', 'peaches'),
				'updateTag' => __('Update Tag', 'peaches'),
				'addTag' => __('Add Tag', 'peaches'),
				'autoGenerated' => __('Auto-generated from label', 'peaches'),
				'manualOverride' => __('Manual override active', 'peaches'),
			)
		));
	}

	/**
	 * Render admin page content for tab integration
	 *
	 * @since 0.2.0
	 *
	 * @return void
	 */
	public function render_admin_page_content() {
		$tags = $this->get_all_tags();
		?>
		<div class="d-flex justify-content-between align-items-start mb-4">
			<div>
				<h3 class="mb-2"><?php esc_html_e('Media Tags Management', 'peaches'); ?></h3>
				<p class="text-muted"><?php esc_html_e('Manage predefined media tags that can be used across all products. Each product can assign one media item per tag.', 'peaches'); ?></p>
			</div>
			<button type="button" class="btn btn-primary text-nowrap" data-bs-toggle="modal" data-bs-target="#addTagModal">
				<i class="dashicons dashicons-plus-alt2"></i>
				<?php esc_html_e('Add New Tag', 'peaches'); ?>
			</button>
		</div>

		<?php $this->render_notices(); ?>

		<div class="row mt-4">
			<div class="col-12">
				<div class="card">
					<div class="card-header d-flex justify-content-between align-items-center">
						<h5 class="card-title mb-0"><?php esc_html_e('Media Tags', 'peaches'); ?></h5>
						<span class="badge bg-secondary"><?php echo count($tags); ?> <?php esc_html_e('tags', 'peaches'); ?></span>
					</div>
					<div class="card-body">
						<?php if (empty($tags)): ?>
							<div class="text-center py-5">
								<i class="dashicons dashicons-tag" style="font-size: 64px; color: #dee2e6; margin-bottom: 16px;"></i>
								<h4 class="text-muted"><?php esc_html_e('No media tags found', 'peaches'); ?></h4>
								<p class="text-muted mb-4"><?php esc_html_e('Create your first media tag to get started organizing your product media.', 'peaches'); ?></p>
								<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addTagModal">
									<i class="dashicons dashicons-plus-alt2"></i>
									<?php esc_html_e('Create First Tag', 'peaches'); ?>
								</button>
							</div>
						<?php else: ?>
							<div class="table-responsive">
								<table class="table table-hover align-middle">
									<thead class="table-light">
										<tr>
											<th scope="col" class="border-0"><?php esc_html_e('Name', 'peaches'); ?></th>
											<th scope="col" class="border-0"><?php esc_html_e('Tag', 'peaches'); ?></th>
											<th scope="col" class="border-0"><?php esc_html_e('Category', 'peaches'); ?></th>
											<th scope="col" class="border-0"><?php esc_html_e('Description', 'peaches'); ?></th>
											<th scope="col" class="border-0 text-end"><?php esc_html_e('Actions', 'peaches'); ?></th>
										</tr>
									</thead>
									<tbody id="media-tags-list">
										<?php foreach ($tags as $tag_key => $tag_data): ?>
											<?php $this->render_tag_row($tag_key, $tag_data); ?>
										<?php endforeach; ?>
									</tbody>
								</table>
							</div>
						<?php endif; ?>
					</div>
				</div>

				<!-- Category Reference Card -->
				<div class="card mt-4">
					<div class="card-header">
						<h6 class="card-title mb-0">
							<i class="dashicons dashicons-info"></i>
							<?php esc_html_e('Tag Categories Reference', 'peaches'); ?>
						</h6>
					</div>
					<div class="card-body">
						<div class="row g-3">
							<div class="col-md-3">
								<div class="d-flex align-items-center">
									<span class="badge bg-primary me-2">Primary</span>
									<small class="text-muted"><?php esc_html_e('Main product images', 'peaches'); ?></small>
								</div>
							</div>
							<div class="col-md-3">
								<div class="d-flex align-items-center">
									<span class="badge bg-secondary me-2">Secondary</span>
									<small class="text-muted"><?php esc_html_e('Additional views', 'peaches'); ?></small>
								</div>
							</div>
							<div class="col-md-3">
								<div class="d-flex align-items-center">
									<span class="badge bg-info me-2">Reference</span>
									<small class="text-muted"><?php esc_html_e('Charts, guides', 'peaches'); ?></small>
								</div>
							</div>
							<div class="col-md-3">
								<div class="d-flex align-items-center">
									<span class="badge bg-warning text-dark me-2">Media</span>
									<small class="text-muted"><?php esc_html_e('Videos, rich content', 'peaches'); ?></small>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Add Tag Modal -->
		<div class="modal fade" id="addTagModal" tabindex="-1" aria-labelledby="addTagModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="addTagModalLabel">
							<i class="dashicons dashicons-plus-alt2"></i>
							<?php esc_html_e('Add New Media Tag', 'peaches'); ?>
						</h5>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<form id="add-media-tag-form">
						<div class="modal-body">
							<?php wp_nonce_field('add_media_tag', 'media_tag_nonce'); ?>

							<div class="mb-3">
								<label for="tag_label" class="form-label"><?php esc_html_e('Display Label', 'peaches'); ?> <span class="text-danger">*</span></label>
								<input type="text"
									   class="form-control"
									   id="tag_label"
									   name="tag_label"
									   placeholder="Hero Image"
									   required>
								<div class="form-text"><?php esc_html_e('Human-readable name shown in the admin interface.', 'peaches'); ?></div>
							</div>

							<div class="mb-3">
								<label for="tag_key" class="form-label"><?php esc_html_e('Tag Key', 'peaches'); ?> <span class="text-danger">*</span></label>
								<input type="text"
									   class="form-control"
									   id="tag_key"
									   name="tag_key"
									   pattern="[a-z0-9_]+"
									   placeholder="hero_image"
									   required>
								<div class="form-text"><?php esc_html_e('Auto-generated from label. Lowercase letters, numbers, and underscores only.', 'peaches'); ?></div>
								<div class="invalid-feedback"></div>
							</div>

							<div class="mb-3">
								<label for="tag_description" class="form-label"><?php esc_html_e('Description', 'peaches'); ?></label>
								<textarea class="form-control"
										  id="tag_description"
										  name="tag_description"
										  rows="3"
										  placeholder="<?php esc_attr_e('Brief description of when to use this tag...', 'peaches'); ?>"></textarea>
								<div class="form-text"><?php esc_html_e('Optional description to help users understand when to use this tag.', 'peaches'); ?></div>
							</div>

							<div class="mb-3">
								<label for="tag_category" class="form-label"><?php esc_html_e('Category', 'peaches'); ?></label>
								<select class="form-select" id="tag_category" name="tag_category">
									<option value="primary"><?php esc_html_e('Primary - Main product images', 'peaches'); ?></option>
									<option value="secondary"><?php esc_html_e('Secondary - Additional product views', 'peaches'); ?></option>
									<option value="reference"><?php esc_html_e('Reference - Size charts, ingredients', 'peaches'); ?></option>
									<option value="media"><?php esc_html_e('Media - Videos and rich media', 'peaches'); ?></option>
								</select>
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
								<?php esc_html_e('Cancel', 'peaches'); ?>
							</button>
							<button type="submit" class="btn btn-primary">
								<i class="dashicons dashicons-plus-alt2"></i>
								<?php esc_html_e('Add Tag', 'peaches'); ?>
							</button>
						</div>
					</form>
				</div>
			</div>
		</div>

		<!-- Edit Tag Modal -->
		<div class="modal fade" id="editTagModal" tabindex="-1" aria-labelledby="editTagModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="editTagModalLabel">
							<i class="dashicons dashicons-edit"></i>
							<?php esc_html_e('Edit Media Tag', 'peaches'); ?>
						</h5>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<form id="edit-media-tag-form">
						<div class="modal-body">
							<?php wp_nonce_field('edit_media_tag', 'edit_media_tag_nonce'); ?>
							<input type="hidden" id="edit_tag_key" name="edit_tag_key" value="">

							<div class="mb-3">
								<label for="edit_tag_label" class="form-label"><?php esc_html_e('Display Label', 'peaches'); ?> <span class="text-danger">*</span></label>
								<input type="text"
									   class="form-control"
									   id="edit_tag_label"
									   name="edit_tag_label"
									   required>
							</div>

							<div class="mb-3">
								<label for="edit_tag_description" class="form-label"><?php esc_html_e('Description', 'peaches'); ?></label>
								<textarea class="form-control"
										  id="edit_tag_description"
										  name="edit_tag_description"
										  rows="3"></textarea>
							</div>

							<div class="mb-3">
								<label for="edit_tag_category" class="form-label"><?php esc_html_e('Category', 'peaches'); ?></label>
								<select class="form-select" id="edit_tag_category" name="edit_tag_category">
									<option value="primary"><?php esc_html_e('Primary - Main product images', 'peaches'); ?></option>
									<option value="secondary"><?php esc_html_e('Secondary - Additional product views', 'peaches'); ?></option>
									<option value="reference"><?php esc_html_e('Reference - Size charts, ingredients', 'peaches'); ?></option>
									<option value="media"><?php esc_html_e('Media - Videos and rich media', 'peaches'); ?></option>
								</select>
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
								<?php esc_html_e('Cancel', 'peaches'); ?>
							</button>
							<button type="submit" class="btn btn-primary">
								<i class="dashicons dashicons-saved"></i>
								<?php esc_html_e('Update Tag', 'peaches'); ?>
							</button>
						</div>
					</form>
				</div>
			</div>
		</div>
		<?php
	}

	/**
	 * Render admin page (kept for backward compatibility)
	 *
	 * @deprecated Use render_admin_page_content() for tab integration
	 */
	public function render_admin_page() {
		?>
		<div class="wrap">
			<h1><?php esc_html_e('Media Tags Management', 'peaches'); ?></h1>
			<?php $this->render_admin_page_content(); ?>
		</div>
		<?php
	}

	/**
	 * Render a tag row.
	 *
	 * @param string $tag_key  Tag key
	 * @param array  $tag_data Tag data
	 */
	private function render_tag_row($tag_key, $tag_data) {
		$category_badges = array(
			'primary' => 'bg-primary',
			'secondary' => 'bg-secondary',
			'reference' => 'bg-info',
			'media' => 'bg-warning text-dark'
		);

		$badge_class = isset($category_badges[$tag_data['category']]) ? $category_badges[$tag_data['category']] : 'bg-secondary';
		$is_default = array_key_exists($tag_key, self::DEFAULT_TAGS);
		?>
		<tr class="media-tag-row" data-tag-key="<?php echo esc_attr($tag_key); ?>">
			<td>
				<div class="d-flex align-items-center">
					<div>
						<h6 class="mb-1"><?php echo esc_html($tag_data['label']); ?></h6>
					</div>
				</div>
			</td>
			<td>
				<code class="bg-ligt px-2 py-1 rounded text-dark text-nowrap"><?php echo esc_html($tag_key); ?></code>
				<div>
				<?php if ($is_default): ?>
					<small class="text-muted hstack mt-1">
						<i class="dashicons dashicons-lock"></i>
						<?php esc_html_e('Default tag', 'peaches'); ?>
					</small>
				<?php endif; ?>
				</div>
			</td>
			<td>
				<span class="badge <?php echo esc_attr($badge_class); ?>">
					<?php echo esc_html(ucfirst($tag_data['category'])); ?>
				</span>
			</td>
			<td>
				<?php if (!empty($tag_data['description'])): ?>
					<span class="text-muted"><?php echo esc_html($tag_data['description']); ?></span>
				<?php else: ?>
					<em class="text-muted"><?php esc_html_e('No description', 'peaches'); ?></em>
				<?php endif; ?>
			</td>
			<td class="text-end">
				<div class="btn-group btn-group-sm" role="group">
					<button type="button"
							class="btn btn-outline-primary edit-tag-btn"
							data-tag-key="<?php echo esc_attr($tag_key); ?>"
							data-tag-label="<?php echo esc_attr($tag_data['label']); ?>"
							data-tag-description="<?php echo esc_attr($tag_data['description']); ?>"
							data-tag-category="<?php echo esc_attr($tag_data['category']); ?>"
							data-bs-toggle="tooltip"
							title="<?php esc_attr_e('Edit tag', 'peaches'); ?>">
						<i class="dashicons dashicons-edit"></i>
						<span class="visually-hidden"><?php esc_html_e('Edit', 'peaches'); ?></span>
					</button>
					<?php if (!$is_default): ?>
						<button type="button"
								class="btn btn-outline-danger delete-tag-btn"
								data-tag-key="<?php echo esc_attr($tag_key); ?>"
								data-tag-label="<?php echo esc_attr($tag_data['label']); ?>"
								data-bs-toggle="tooltip"
								title="<?php esc_attr_e('Delete tag', 'peaches'); ?>">
							<i class="dashicons dashicons-trash"></i>
							<span class="visually-hidden"><?php esc_html_e('Delete', 'peaches'); ?></span>
						</button>
					<?php else: ?>
						<button type="button"
								class="btn btn-outline-secondary"
								disabled
								data-bs-toggle="tooltip"
								title="<?php esc_attr_e('Default tags cannot be deleted', 'peaches'); ?>">
							<i class="dashicons dashicons-lock"></i>
							<span class="visually-hidden"><?php esc_html_e('Protected', 'peaches'); ?></span>
						</button>
					<?php endif; ?>
				</div>
			</td>
		</tr>
		<?php
	}

	/**
	 * Render notices.
	 */
	private function render_notices() {
		if (isset($_GET['message'])) {
			$message = sanitize_text_field($_GET['message']);
			$type = isset($_GET['type']) ? sanitize_text_field($_GET['type']) : 'success';

			$alert_class = $type === 'error' ? 'alert-danger' : 'alert-success';
			?>
			<div class="alert <?php echo esc_attr($alert_class); ?> alert-dismissible fade show">
				<?php echo esc_html(urldecode($message)); ?>
				<button type="button" class="btn-close" data-bs-dismiss="alert"></button>
			</div>
			<?php
		}
	}

	/**
	 * Handle form submission.
	 */
	public function handle_form_submission() {
		// This will be handled via AJAX, but keeping for fallback
	}

	/**
	 * AJAX: Add media tag.
	 */
	public function ajax_add_media_tag() {
		check_ajax_referer('media_tags_nonce', 'nonce');

		if (!current_user_can('manage_options')) {
			wp_send_json_error(__('Insufficient permissions.', 'peaches'));
		}

		$tag_key = sanitize_key($_POST['tag_key']);
		$tag_label = sanitize_text_field($_POST['tag_label']);
		$tag_description = sanitize_textarea_field($_POST['tag_description']);
		$tag_category = sanitize_text_field($_POST['tag_category']);

		if (empty($tag_key) || empty($tag_label)) {
			wp_send_json_error(__('Tag key and label are required.', 'peaches'));
		}

		// Validate tag key format
		if (!preg_match('/^[a-z0-9_]+$/', $tag_key)) {
			wp_send_json_error(__('Tag key can only contain lowercase letters, numbers, and underscores.', 'peaches'));
		}

		$tags = $this->get_all_tags();

		if (isset($tags[$tag_key])) {
			wp_send_json_error(__('A tag with this key already exists.', 'peaches'));
		}

		$tags[$tag_key] = array(
			'label' => $tag_label,
			'description' => $tag_description,
			'category' => $tag_category
		);

		update_option(self::TAGS_OPTION, $tags);

		wp_send_json_success(array(
			'message' => __('Tag added successfully.', 'peaches'),
			'tag_key' => $tag_key,
			'tag_data' => $tags[$tag_key]
		));
	}

	/**
	 * AJAX: Delete media tag.
	 */
	public function ajax_delete_media_tag() {
		check_ajax_referer('media_tags_nonce', 'nonce');

		if (!current_user_can('manage_options')) {
			wp_send_json_error(__('Insufficient permissions.', 'peaches'));
		}

		$tag_key = sanitize_key($_POST['tag_key']);

		if (empty($tag_key)) {
			wp_send_json_error(__('Tag key is required.', 'peaches'));
		}

		// Prevent deletion of default tags
		if (array_key_exists($tag_key, self::DEFAULT_TAGS)) {
			wp_send_json_error(__('Default tags cannot be deleted.', 'peaches'));
		}

		$tags = $this->get_all_tags();

		if (!isset($tags[$tag_key])) {
			wp_send_json_error(__('Tag not found.', 'peaches'));
		}

		unset($tags[$tag_key]);
		update_option(self::TAGS_OPTION, $tags);

		wp_send_json_success(array(
			'message' => __('Tag deleted successfully.', 'peaches')
		));
	}

	/**
	 * AJAX: Update media tag.
	 */
	public function ajax_update_media_tag() {
		check_ajax_referer('media_tags_nonce', 'nonce');

		if (!current_user_can('manage_options')) {
			wp_send_json_error(__('Insufficient permissions.', 'peaches'));
		}

		$tag_key = sanitize_key($_POST['tag_key']);
		$tag_label = sanitize_text_field($_POST['tag_label']);
		$tag_description = sanitize_textarea_field($_POST['tag_description']);
		$tag_category = sanitize_text_field($_POST['tag_category']);

		if (empty($tag_key) || empty($tag_label)) {
			wp_send_json_error(__('Tag key and label are required.', 'peaches'));
		}

		$tags = $this->get_all_tags();

		if (!isset($tags[$tag_key])) {
			wp_send_json_error(__('Tag not found.', 'peaches'));
		}

		$tags[$tag_key] = array(
			'label' => $tag_label,
			'description' => $tag_description,
			'category' => $tag_category
		);

		update_option(self::TAGS_OPTION, $tags);

		wp_send_json_success(array(
			'message' => __('Tag updated successfully.', 'peaches'),
			'tag_data' => $tags[$tag_key]
		));
	}

	/**
	 * Get all media tags.
	 *
	 * @return array Array of media tags
	 */
	public function get_all_tags() {
		return get_option(self::TAGS_OPTION, array());
	}

	/**
	 * Get tags by category.
	 *
	 * @param string $category Category to filter by
	 *
	 * @return array Array of filtered tags
	 */
	public function get_tags_by_category($category) {
		$all_tags = $this->get_all_tags();
		return array_filter($all_tags, function($tag_data) use ($category) {
			return isset($tag_data['category']) && $tag_data['category'] === $category;
		});
	}

	/**
	 * Get tag data by key.
	 *
	 * @param string $tag_key Tag key
	 *
	 * @return array|null Tag data or null if not found
	 */
	public function get_tag($tag_key) {
		$tags = $this->get_all_tags();
		return isset($tags[$tag_key]) ? $tags[$tag_key] : null;
	}

	/**
	 * Check if tag exists.
	 *
	 * @param string $tag_key Tag key
	 *
	 * @return bool True if tag exists
	 */
	public function tag_exists($tag_key) {
		$tags = $this->get_all_tags();
		return isset($tags[$tag_key]);
	}
}
